//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int LogID { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string Action { get; set; }
        public string Details { get; set; }
    
        public virtual Admin_tbl Admin_tbl { get; set; }
    }
}
