//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Devices_tbl()
        {
            this.DeviceAssignment_tbl = new HashSet<DeviceAssignment_tbl>();
        }
    
        public int DeviceID { get; set; }
        public Nullable<int> DeviceTypeID { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastMaintenanceDate { get; set; }
        public string Retired { get; set; }
        public string Details { get; set; }
    
        public virtual Device_Type_tbl Device_Type_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceAssignment_tbl> DeviceAssignment_tbl { get; set; }
    }
}
