//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceAssignment_tbl
    {
        public int AssignmentID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<int> AssignedToEmployeeID { get; set; }
        public Nullable<int> AssignedByAdminID { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Notes { get; set; }
        public string Returned { get; set; }
        public string SerialNumber { get; set; }
        public string AssignedToEmployee { get; set; }
        public string AssignedByAdmin { get; set; }
    
        public virtual Admin_tbl Admin_tbl { get; set; }
        public virtual Devices_tbl Devices_tbl { get; set; }
        public virtual Employee_tbl Employee_tbl { get; set; }
    }
}
