//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory_Sys.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastAssignment_tbl
    {
        public int PastID { get; set; }
        public string AssignedTo { get; set; }
        public string AssignedBy { get; set; }
        public Nullable<System.DateTime> AssignmentDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public string Notes { get; set; }
        public string Returned { get; set; }
        public string SerialNumber { get; set; }
    }
}
